version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: axolotl
      POSTGRES_USER: axolotl
      POSTGRES_PASSWORD: 186Kdc9899K
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - axolotl_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 186Kdc9899K
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/axolotl
      KC_DB_USERNAME: axolotl
      KC_DB_PASSWORD: 186Kdc9899K
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  discover:
    container_name: discover
    image: discover
    restart: always
    ports:
      - "8761:8761"

  eureka-gateway:
    container_name: eureka-gateway
    image: eureka-gateway
    depends_on:
      - discover
    restart: always
    environment:
       IP: discover
    ports:
      - "8000:8000"


networks:
  axolotl_network:
    driver: bridge

volumes:
  pgdata: