server:
  port: 9001
  address: 0.0.0.0



logging:
  level:
    root: INFO              # уровень логирования по умолчанию
    org.springframework: INFO
    org.your.package: DEBUG  # свой пакет, если нужно подробный лог
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

spring:
  kafka:
      bootstrap-servers: ${KAFKA_URL:192.168.31.34}:9094
  application:
    name: auth

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${IP:192.186.31.50}
    instance-id: ${IP:192.186.31.50}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_IP:192.168.31.34}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


secured: ${SECURED_HTTP:http}
secret: ${SECRET:wuqUtDJ1oJi3GFKOmNF4DPgyULFv20ZO}