server:
  port: 9001
  address: ${IP:192.168.31.50}

logging:
  level:
    root: INFO              # уровень логирования по умолчанию
    org.springframework: INFO
    org.your.package: DEBUG  # свой пакет, если нужно подробный лог
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

spring:
  kafka:
      bootstrap-servers: ${KAFKA_URL:localhost:9094}
  application:
    name: auth

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


secured: ${SECURED_HTTP:http}