server:
  port: 9001
  address: ${IP:192.168.0.165}

logging:
  file:
    name: logs/app.log
spring:
  kafka:
      bootstrap-servers: ${KAFKA_URL:localhost:9094}
  application:
    name: auth
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:5432/axolotl"
    username: axolotl
    password: 186Kdc9899K
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


secured: ${SECURED_HTTP:http}