server:
  port: 9001
  address: 0.0.0.0

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:5432/axolotl"
    username: axolotl
    password: 186Kdc9899K
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${KEYCLOAK_HOST:localhost}:8080/realms/axolotl"


secured: ${SECURED_HTTP:http}